# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5133ff1f7083e45d88909bee8f0f9ecb6b6096e22a8c580ca22edac5ef9b08cd24e374f95786a22e2a1267bde441119ca863104dde98852696d80b3f332679

test:
  secret_key_base: acb609366732bba1be7548708832e2b82e8aac5d50b8f1b386c2c40283d0796bcba799553cfd3c53c4a338cab559f37cfe987d6caf45c5f60afbd39435c50354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
